### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by Hardik-Ahi** [Jatin020403/Space-Defence#1]
Typo in README.md:

"school assignment and uses myultiple types"

'myultiple types'

*myultiple*

Removing the 'y' should fix that.

**Comment by Jatin020403** [comment]
@Hardik-Ahi 😭😭😭

**Comment by Jatin020403** [comment]
who makes the pr?! I think you coz you spotted it

And this is the first time am getting to play with issues
